### ISSUE TITLE
I like the name of your org

### ISSUE THREAD

**Issue by nachtgold** [CarPlan/CarPlan#7]
Hi @JeffersonJeffrey , @Kauruck @Gentleman-DE ,
I'd like to use the name carplan for my project and I've seen your project is somewhat outdated. Is it possible for you to rename your github ORG ?

Best Regards 
Kai

**Comment by Kauruck** [comment]
Hallo Kai,
I have renamed our organisation. Hope you can now get the name.

With Best Regards
Kauruck

**Comment by nachtgold** [comment]
Hi Kauruck, thank you very much. You are the best 💯
